---
---

<link rel="stylesheet" href="styles.css" type="text/css" >

<center>

# Some Personal Poems

## I Wish I Could Tell You

*I Wish I Could Tell You*

How the house I'm living in is no longer a home

That I only feel okay when I'm completely alone

How sometimes I wish I lived in a different time-zone

To avoid feeling miserable, to have some time on my own

As bad as I feel, it's hard to let these feelings be known

Because I am a 21 year old woman who has to act "grown"

Who has to dry her tears and not let her feelings be shown

So I'll continue this battle and just keep dodging the stones

*I Wish I Could Tell You*

About the amount of scars I hide

Not only physical but the ones that creep from inside

From every friend I thought I had yet they always said goodbye

From the days I spent in High School avoiding lunchtime

And no matter how hard I tried, I was always left behind

Always makes me contemplate why I was never ever liked

According to them I was boring and way too shy

While I tried my hardest to fit into each of their paradise

The picture wasn't bright enough, they didnt see how we were alike

I was never good enough, my frienship was constantly denied

*I Wish I Could Tell You*

How at 13 I watched my family fall apart

How the cops barged in, pointing their guns

At night I can still hear the barking of their dogs

But little did I know they were only doing their job

One parent tried to hurt the other so they called the cops

That's when I realized daddy's little girl had to grow up

Still remember being frozen and doing nothing but sob

Why do people hurt the person they claim to love


## Insomnia

Insomnia's The fly that won't stop buzzing in your ear

Keeps you up at night and tells you all the things you hate to hear

It feeds off of your pain, worries, and fears

It reminds you of the people you know but are no longer here

It tricks you into thinking you're finally falling asleep

Until sleep paralysis hits you and you start hyperventilating

<center>





